# Generated by Django 2.1 on 2018-08-30 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_value', models.FloatField(default=0.0, verbose_name='A Value')),
                ('b_value', models.FloatField(default=0.0, verbose_name='B Value')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sites.SiteName')),
            ],
        ),
    ]
